import type { Metadata } from "next";
import "./globals.css";
// import { ThemeProvider } from "@/components/ThemeProvider";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { cn } from "@/lib/utils";
import { AuthProvider } from "@/components/auth/AuthProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(GeistSans.className, GeistMono.className, "antialiased")}
    >
      <AuthProvider>
        <body>{children}</body>
      </AuthProvider>
    </html>
  );
}
